### ISSUE TITLE
OS X SDK

### ISSUE THREAD

**Issue by fanktom** [kent-displays/boogie-board-sync-ios-sdk#2]
Hey there,

great that you have a iOS SDK. As I'm not really happy with the Boogy Board Sync App on OSX (Too much Interface, broken Sync to Folder) I would love to create a simple OSX Menulet that allows plain syncing to a folder on save.

Could you maybe create an OSX SDK as well, so developers can use the default syncing mechanisms without going through all the IOBluetooth, OBEX stuff?

Thanks for your help!

**Comment by camdenfullmer** [comment]
@southdesign, at this time we have no plans to introduce an SDK for OS X.

That being said, if you were interested in creating a SDK I could help get you started. We do have protocol documentation on how the communication works over Bluetooth and USB that would be valuable.

**Comment by fanktom** [comment]
Sounds great. Maybe the specs + some code from the ios sdk can get the job done quickly.

You think it could be a good idea to create a framework á la CoreBoogieBoard that both, the ios sdk and a mac sdk could use?

**Comment by camdenfullmer** [comment]
Here is a link to our spec we have internally: https://www.dropbox.com/s/i72o4739wmns9b1/25196c_BB_Sync_Communication_Protocol.pdf?dl=0

Unfortunately, having a framework for both iOS and OS X is not very likely. The communication with the Boogie Board Sync is based on standard HID and Bluetooth FTP protocols. These protocols are written from scratch on iOS since they are not provided by Apple.

On OS X, these protocols are already implemented and are easy to access and use. The only thing that has to be written is the custom logic that the Boogie Board Sync uses. To download files from the Sync just use `OBEXFileTransferServices` API that Apple provides.

**Comment by fanktom** [comment]
Great, thanks. Talk to you soon when I've had the chance to test the implementation.

Besides from the `OBEXFileTransferServices` API I need to listen for the `SAVE` action to initiate a sync. Any ideas on how that could be done on OS X?

**Comment by camdenfullmer** [comment]
To know when the Sync saves a file, you have to use the other communication protocol (HID). By using `IOHIDManager` and `IOHIDDevice` you will receive input reports from the Sync, there is more detail in the protocol spec.

**Comment by fanktom** [comment]
Alright, thanks!

**Comment by camdenfullmer** [comment]
@southdesign closing this issue. If you want to discuss further, I would suggest making a repo and I can help out there.
